### ISSUE TITLE
file screening message

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#124]
File has errors, please correct the errors before **uploding** to the database.
Please correct to:
File has errors, please correct the errors before **uploading** to the database.

**Comment by peterdesmet** [comment]
Also `Our team will check with happend` rather than `happened`

**Comment by nicolasvanermen** [comment]
This latter typo is in the submission email... Also the subject of this email ('Success inserting the file into the database AccessionID [20222859]' ) is contradictory to the content of the message ('We are sorry to report that there was an issue inserting the file (ESAS_BE_DATA_final.csv) with Accession 20222859 into the database.')

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/195375001-ac1a8ced-7a9e-4f5e-93d2-c8091836f559.png)

**Comment by cmspinto** [comment]
Both these should be fixed

**Comment by nicolasvanermen** [comment]
This is not fixed yet:
![image](https://user-images.githubusercontent.com/7381853/203527761-349dd6b5-f7b8-4ccb-9f11-8c5368f51d9a.png)

**Comment by cmspinto** [comment]
Should be fixed now, thanks for the heads up.
